#!/usr/bin/env python3
"""Build apps/homelab_base/default/savedsearches.conf from detections/**/*.spl.

The .spl files are the single source of truth. Each starts with a ``` comment
header holding `Key: value` lines. This script uses Name, Cron and Window
("<earliest> to <latest>"); continuation lines (indented, no key) belong to the
previous key. Everything after the header is the search.

Every search is a scheduled report with no alert action, so it also runs on
Splunk Free. Detections end in `collect index=soc_alerts` (the alert queue).
Run it after editing a detection, then deploy with splunk/server/deploy-app.sh.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "detections"
OUT = ROOT / "splunk/apps/homelab_base/default/savedsearches.conf"


def parse(path):
    text = path.read_text()
    m = re.match(r"\s*```(.*?)```\s*(.*)", text, re.S)
    if not m:
        sys.exit(f"{path}: no ``` header")
    header, body = m.groups()
    meta, key = {}, None
    for line in header.splitlines():
        km = re.match(r"\s*([A-Za-z][A-Za-z &]*?):\s+(.*)", line)
        if km:
            key = km.group(1)
            meta[key] = km.group(2).strip()
        elif key and line.strip():
            meta[key] += " " + line.strip()
    for k in ("Name", "Cron", "Window"):
        if k not in meta:
            sys.exit(f"{path}: header lacks {k}:")
    earliest, latest = [w.strip() for w in meta["Window"].split(" to ")]
    lines = [l.rstrip() for l in body.strip().splitlines()]
    if any(l.endswith("\\") for l in lines):
        sys.exit(f"{path}: a search line ends in a backslash (breaks .conf continuation)")
    return meta, earliest, latest, lines


def stanza(path, meta, earliest, latest, lines):
    baseline = path.parent.name == "baselines"
    title = meta["Name"] if baseline else f"Detection - {meta['Name']}"
    desc = meta.get("Purpose") or meta.get("ATT&CK", "")
    rel = path.relative_to(ROOT)
    return "\n".join([
        f"# Generated from {rel}. Edit that file, not this one.",
        f"[{title}]",
        f"description = {desc} (source: {rel})",
        "search = " + " \\\n".join(lines),
        "enableSched = 1",
        f"cron_schedule = {meta['Cron']}",
        f"dispatch.earliest_time = {earliest}",
        f"dispatch.latest_time = {latest}",
        "schedule_window = 5",
        "alert.track = 0",
        "",
    ])


def main():
    files = sorted(SRC.glob("*.spl")) + sorted((SRC / "baselines").glob("*.spl"))
    parts = ["# GENERATED by splunk/build-savedsearches.py from detections/. Do not edit by hand.\n"]
    for f in files:
        parts.append(stanza(f, *parse(f)))
    OUT.write_text("\n".join(parts))
    print(f"wrote {OUT.relative_to(ROOT)}: {len(files)} searches")


if __name__ == "__main__":
    main()
