#!/usr/bin/env python3
"""Generate docs/inventory.md from the Proxmox API.

Reads Proxmox targets and read-only API tokens from the proxmox-mcp config
(default: $PROXMOX_MCP_CONFIG or ~/.config/proxmox-mcp/config.json), which
lives outside this repo so no credentials are ever committed.

The output has no timestamp on purpose: re-running it only produces a git
diff when the lab actually changed.

Usage: scripts/inventory.py [--config PATH] [--out PATH]
"""

import argparse
import json
import os
import ssl
import sys
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_CONFIG = os.environ.get(
    "PROXMOX_MCP_CONFIG", str(Path.home() / ".config/proxmox-mcp/config.json")
)
NATIVE_VLAN = 5  # untagged traffic on vmbr0 lands on the management VLAN


class Target:
    def __init__(self, name, cfg):
        self.name = name
        self.base = f"https://{cfg['host']}:{cfg.get('port', 8006)}/api2/json"
        auth = cfg["auth"]
        self.header = f"PVEAPIToken={auth['user']}!{auth['token_name']}={auth['token_value']}"
        self.ctx = ssl.create_default_context()
        if not cfg.get("verify_ssl", True):
            self.ctx.check_hostname = False
            self.ctx.verify_mode = ssl.CERT_NONE

    def get(self, path):
        req = urllib.request.Request(self.base + path, headers={"Authorization": self.header})
        with urllib.request.urlopen(req, context=self.ctx, timeout=15) as resp:
            return json.load(resp)["data"]

    def try_get(self, path):
        try:
            return self.get(path)
        except Exception:
            return None


def gib(n):
    if not n:
        return "-"
    return f"{n / 2**20:.0f} MiB" if n < 2**30 else f"{n / 2**30:.0f} GiB"


def parse_kv(s):
    """Parse a Proxmox 'a=1,b=2' option string (first bare value is kept as '_')."""
    out = {}
    for part in (s or "").split(","):
        k, sep, v = part.partition("=")
        if sep:
            out[k] = v
        elif part:
            out["_"] = part
    return out


def live_ip(t, node, kind, vmid):
    if kind == "lxc":
        ifaces = t.try_get(f"/nodes/{node}/lxc/{vmid}/interfaces") or []
        for i in ifaces:
            addr = i.get("inet", "")
            if i.get("name") != "lo" and addr:
                return addr.split("/")[0]
    else:
        res = t.try_get(f"/nodes/{node}/qemu/{vmid}/agent/network-get-interfaces") or {}
        for i in res.get("result", []):
            if i.get("name") == "lo":
                continue
            for a in i.get("ip-addresses", []):
                if a.get("ip-address-type") == "ipv4":
                    return a["ip-address"]
    return None


def guest_row(t, g):
    node, vmid, kind = g["node"], g["vmid"], g["type"]
    cfg = t.try_get(f"/nodes/{node}/{kind}/{vmid}/config") or {}
    net = parse_kv(cfg.get("net0"))
    vlan = net.get("tag", str(NATIVE_VLAN))

    ip = net.get("ip") or parse_kv(cfg.get("ipconfig0")).get("ip") or "dhcp"
    ip = ip.split("/")[0]
    if ip == "dhcp" and g.get("status") == "running":
        ip = live_ip(t, node, kind, vmid) or "dhcp"
        if ip != "dhcp":
            ip += " (dhcp)"

    if g.get("template"):
        role = "template"
    else:
        role = "VM" if kind == "qemu" else "LXC"
    tags = ", ".join(x for x in (g.get("tags") or "").split(";") if x) or "-"
    return (
        f"| {vmid} | {g.get('name', '')} | {role} | {t.name}/{node} | {g.get('status', '')} "
        f"| {g.get('maxcpu', '-')} | {gib(g.get('maxmem'))} | {vlan} | {ip} | {tags} |"
    )


def build(targets):
    lines = [
        "# Inventory",
        "",
        "> Generated by [`scripts/inventory.py`](../scripts/inventory.py) from the Proxmox API. "
        "Do not edit by hand. Re-run the script instead.",
        "",
        "## Nodes",
        "",
        "| Target | Node | Status | CPU threads | RAM |",
        "|---|---|---|---|---|",
    ]
    guests, storage = [], {}
    for t in targets:
        for n in sorted(t.get("/nodes"), key=lambda n: n["node"]):
            lines.append(
                f"| {t.name} | {n['node']} | {n.get('status', '')} | {n.get('maxcpu', '-')} | {gib(n.get('maxmem'))} |"
            )
        for g in t.get("/cluster/resources?type=vm"):
            guests.append((g["vmid"], t, g))
        for s in t.get("/cluster/resources?type=storage"):
            if not s.get("maxdisk"):
                continue  # skip pools with no usable capacity (e.g. unused 'local')
            # Shared storage shows up once per node; list it once per target.
            where = "shared" if s.get("shared") else s["node"]
            storage[(t.name, s["storage"], where)] = s

    lines += [
        "",
        "## Guests",
        "",
        "| ID | Name | Type | Location | Status | vCPU | RAM | VLAN | IP | Tags |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    lines += [guest_row(t, g) for _, t, g in sorted(guests, key=lambda x: x[0])]

    lines += [
        "",
        "## Storage",
        "",
        "| Target | Storage | Type | Node | Used | Size |",
        "|---|---|---|---|---|---|",
    ]
    for (tname, sname, where), s in sorted(storage.items()):
        lines.append(
            f"| {tname} | {sname} | {s.get('plugintype', '')} | {where} | {gib(s.get('disk'))} | {gib(s.get('maxdisk'))} |"
        )
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--config", default=DEFAULT_CONFIG)
    ap.add_argument("--out", default=str(REPO_ROOT / "docs/inventory.md"))
    args = ap.parse_args()

    with open(args.config) as f:
        cfg = json.load(f)
    targets = [Target(name, c) for name, c in sorted(cfg["targets"].items())]
    try:
        md = build(targets)
    except Exception as e:
        sys.exit(f"inventory: {e}")
    Path(args.out).write_text(md)
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
